name: debuilder

on:
  workflow_call:
  push:
    branches:
      - "!*"
    tags:
      - "debian/**"

jobs:
  call-ros-ci-build-melodic:
    uses: LCAS/rosdistro/.github/workflows/_lcas_debuilder.yaml@master
    with:
      ros_distribution: melodic
      docker_image: ubuntu:bionic
    secrets:
      gpg_private_key: ${{ secrets.DEB_SIGN_PRIV_KEY }}
      dockerhub_user: ${{ secrets.DOCKERHUB_USER }}
      dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
      gpg_key_id: ${{ secrets.DEB_SIGN_KEY_ID }}
      repository_user: ${{ secrets.LCAS_REGISTRY_PUSHER }}
      repository_pass: ${{ secrets.LCAS_REGISTRY_TOKEN }}
      

